pipeline {
  agent {
    docker {
      image 'node:16-alpine'
    }
  }

  environment {
    npm_config_cache = './npm-cache'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install') {
      steps {
        dir('frontend') {
          sh 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir('frontend') {
          sh 'npm run build'
        }
      }
    }
  }

  post {
    always {
      echo 'Clean up done.'
    }
  }
}
